### ISSUE TITLE
Is there a trick  to setup the SES example?

### ISSUE THREAD

**Issue by RandoSY** [majbthrd/pico-demos#1]
I'm bombing out on the simple includes ... 

`Building ‘pico-ses’ from solution ‘pico-ses’ in configuration ‘Debug’
  Compiling ‘main.c’
    main.c
    core_cm0plus.h: No such file or directory
  Compiling ‘system_rp2040.c’
    system_rp2040.c
    core_cm0plus.h: No such file or directory
Build failed`

Before I did a lot of debug, I just wanted to ask.

Thanks.

**Comment by majbthrd** [comment]
@RandoSY, I think I know what is going on.  In SEGGER Embedded Studio, go to the pull-down menu Tools > Show Installed Packages

![ses-packages-annotated](https://user-images.githubusercontent.com/12226419/124361747-4b7f3e00-dbf6-11eb-9aad-ba73d7907289.png)

I suspect that you are missing "CMSIS 5 CMSIS-CORE Support Package".

To install this, go to the pull-down menu Tools > Package Manager...  You can type "CMSIS" in the search box in the upper left corner to find it.  Double-click "CMSIS 5 CMSIS-CORE Support Package" (or any other package you want) to select it, and then click the "Next" button to install it.

That should remedy your issue.

P.S.: SEGGER Embedded Studio is based on Rowley Crossstudio for ARM, and Rowley Crossstudio for ARM has the capability for projects to specify package dependencies so that it can auto install them if needed.  I'm looking at the project options in SEGGER Embedded Studio now, and I can't see such an equivalent... it is a nuisance that SEGGER seems to have omitted it.

**Comment by RandoSY** [comment]
Yes, that was it thank you! I had the 4 release, but not the 5 installed. 

The file was hidden on the dependencies section ... 

![SES_Project_snip](https://user-images.githubusercontent.com/609947/124366935-58fded80-dc21-11eb-887d-d85b971ee52e.JPG)

**Comment by majbthrd** [comment]
Cool

**Comment by RandoSY** [comment]
I guess SES is way to proprietary to use with your amazing pico-debug? 

I'm thinking maybe native Eclipse GDB is a candidate. 

Code and sophisticated debug on one chip is out of sight!

**Comment by majbthrd** [comment]
SEGGER claims in press releases that SES supports CMSIS-DAP (the protocol standard supported by [pico-debug](https://github.com/majbthrd/pico-debug/)), but when I inquire why that option doesn't exist, I don't get a satisfactory answer from SEGGER:

https://forum.segger.com/index.php/Thread/7848-ABANDONED-What-happened-to-CMSIS-DAP-DAP-Link-support/

The CMSIS-DAP standard has been around for about eight years, so lots of tools *should* support it.
